config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :canadas do
    get '/main', to: 'canadas#main', as: 'main'
    get '/immigrant', to: 'canadas#immigrant', as: 'immigrant'
    get '/study', to: 'canadas#study', as: 'study'
    get '/work', to: 'canadas#work', as: 'work'
    get '/visit', to: 'canadas#visit', as: 'visit'
    get '/contact-us', to: 'canadas#contact-us', as: 'contact-us'
    get '/display/:id/', to: 'canadas#display', as: 'display'
    collection do
      get '/search', to: 'canadas#search', as: 'search'
    end
  end
    root 'canadas#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/canada.rb
class Canada < ApplicationRecord
  def self.search(search)
  if search
    where(["application_no LIKE ?", "%#{search}%"])
   else
    all
  end
  end
  # validates :passport_no, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
 before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name,:email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/canadas_controller.rb
class CanadasController < ApplicationController
   before_action :authenticate_user!, only:[:main]
  def index

  end

  def display
     @canada = Canada.find(params[:canada_id])

    respond_to do |format|
      format.html
      format.pdf do
       render pdf: "file_name"   # Excluding ".pdf" extension.
      end
    end
  end
  def search
    if params[:search]
      @canada = Canada.search(params[:search]).order("application_no")
    else
      @canada = Canada.all.("application_no")
    end
  end
  def main

  @canadas = Canada.search(params[:search])
  end

  def immigrant

  end

  def study

  end

  def work

  end

  def show
    @canada = Canada.find(params[:id])
  end

  def new
    @canada = Canada.new
  end

  def edit
    @canada = Canada.find(params[:id])
  end

  def create
    @canada = Canada.new(canada_params)

   if @canada.save
       redirect_to @canada

    else
      render 'new'
    end
  end

  def update
    @canada = Canada.find(params[:id])

    if @canada.update(canada_params)
       redirect_to @canada
    else
      render 'edit'
    end
  end

  def destroy
    @canada = Canada.find(params[:id])
    @canada.destroy

    redirect_to canada_main_path(:can)
  end

  private
  def canada_params
    params.require(:canada).permit(:application_no, :first_name, :surname, :last_name, :nationality, :passport_no, :passport_expiry, :visa_category, :date_time, :application_status, :marital_status,:sponsor, :jobcat, :sponsor_name, :sponsor_Id, :sponsor_license, :sponsor_business, :sponsor_taxation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canadas_helper.rb
module CanadasHelper
end

app/views/canadas/immigrant.html.erb
<body style="overflow-x: hidden;">
  <div class="container">
    <div class="row" style="margin-top: -32px;">
      <div class="col-md-3 o1">
        <%= link_to canadas_path do %>
         <%= image_tag "can1"%>
        <%end%>
      </div>
      <div class="col-md-9 o2" style="padding: 0px;">
        <%= image_tag "we", class: "mySlides img-fluid"%>
        <%= image_tag "visi", class: "mySlides img-fluid"%>
        <%= image_tag "imii", class: "mySlides img-fluid"%>
        <%= image_tag "study", class: "mySlides img-fluid"%>
        <%= image_tag "wok", class: "mySlides img-fluid"%>
      </div>
    </div>
    <script type="text/javascript">
      var myIndex = 0;
      carousel();

      function carousel()
      {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++)
        {
         x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) {myIndex = 1}
        x[myIndex-1].style.display = "block";
        setTimeout(carousel, 5000); // Change image every 2 seconds
      }
    </script>
    <div class="row">
      <div class="col-md-12" style="margin-top: -51px;">
        <p  class="pic2"></p>
      </div>
    </div>

    <div style="margin-top: -74px;" class="row">
      <div class="col-md-4">
        <div class="dropdown-show" style="margin-top: -26px;  margin-left: -14px; padding: 11px;">
          <a class="btn btn-light dropdown-toggle" href="#" role="button" id="                               dropdownMenuLink" data-toggle="dropdown"> Menu
          </a>
          <div class="dropdown-menu" >
            <%= link_to 'visit', canada_visit_path(:visa), class: "dropdown-item" %>
            <%= link_to 'immigrant', canada_immigrant_path(:visa), class: "dropdown-item" %>
            <%= link_to 'study', canada_study_path(:visa), class: "dropdown-item" %>
            <%= link_to 'work', canada_work_path(:visa), class: "dropdown-item" %>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="container">
          <marquee style="margin-left: -314px;">
            <span>Avail your canada visa from here |</span>&nbsp;
            <span> Study visa |</span>&nbsp;
            <span>Immigration |</span>&nbsp;
            <span>Visit visa |</span>&nbsp;
            <span>Work permit visa |</span>&nbsp;
            <span>Best place to get any type of canada visa</span>
          </marquee>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="mwscolumn section">
        <div class="row" style="margin-top: 48px;">
          <div class="col-md-5">
            <div class="mwstitle section">
              <h1 id="imi">For new immigrants</h1>
              <p class="jk"></p>
              <p>Apply for a permanent resident card or Canadian citizenship and find out about how to start your life in Canada. Also find out what services are near you to help and what to expect for your first tax year.</p>
            </div>
          </div>
          <div class="col-md-7">
              <%= image_tag "imi",class: "img-fluid" %>
            </div>
          </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container" style="margin-top: 30px;">
      <h2><strong>How to get canadian permanent resident</strong></h2>
      <p>In order to initiate the Canada PR process, contact the nearest consulate, high commission or an embassy of Canada. At the basic level, obtaining a permanent resident visa requires the individual to:</p>
      <ul>
        <li>Provide a medical certificate and criminal record check</li>
        <li>Fill in and submit a permanent resident visa application</li>
        <li>Pay the application fee</li>
        <li>Attend interviews with immigration representatives</li>
      </ul>
      <p>In addition, and depending on the nature and category of your application, the following may or may not be required:</p>
      <ul>
        <li>Originals, copies and official translations of documents that support the application including educational degrees, diplomas, and certificates, personal identification documents and/or sponsor letters and relevant information</li>
        <li>Sufficient funds to support the applicant during the initial time in Canada</li>
        <li>Skills assessment test</li>
        <li>Proof of refugee status</li>
        <li>Language test(s) results</li>
        <li>Additional fees</li>
        <li>Other documentation or tests</li>
      </ul>
      <h2><strong>Determine if you're eligible for a permanent resident status</strong></h2>
      <p>Calculate your score in the CRS system for Express Entry. Add all the point that you may obtain through examining the categories of age, level of education, official language proficiency, second official language, and canadian work experience. Furthermore, applicants need to be able to prove that they have sufficient funds to support themselves and their family, unless they can already legally work in or have a valid job offer from an employer in Canada.</p>
      <h2><strong>Who can apply for permanent resident status?</strong></h2>
      <p>Anyone is allowed to apply for permanent residency in Canada but only qualified individuals will be accepted. To find if you are eligible for permanent residency you will be examined by your age, level of education, official language proficiency, second official language and Canadian work experience.</p>
      <div style="text-align: center;">
        <%= link_to "Apply now", new_canada_path, class: "btn btn-dark"  %>
      </div>
    </div>
    <div class="brand" id="brand_imi">
      <div class="container" style="margin-top: 26px; margin-bottom: 1px;">
        <div class="row">
          <nav class="col-sm-10 ftr-urlt-lnk">
            <ul class="list-group flex-md-row">
              <li style="margin-right: 27px;">Social-Media</li>
              <li style="margin-right: 27px;">Mobile-Application</li>
              <li style="margin-right: 27px;">Canada.Ca</li>
              <li style="margin-right: 27px;">Term&Condition</li>
              <li>Privacy</li>
            </ul>
          </nav>
          <div class="col-xs-6 col-md-2 text-right" style="margin-left: -85px;">
           <%= link_to canada_main_path(:can) do %>
           <%= image_tag "last"%>
           <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/canadas/index.html.erb
<body style="overflow-x: hidden;">
<div class="container">
  <div class="row" style="margin-top: -32px;">
    <div class="col-md-3 o1">
    <%= link_to canadas_path do %>
      <%= image_tag "can1"%>
    <%end%>
</div>
<div class="col-md-9 o2" style="padding: 0px;">
    <%= image_tag "we", class: "mySlides img-fluid"%>
    <%= image_tag "visi", class: "mySlides img-fluid"%>
    <%= image_tag "imii", class: "mySlides img-fluid"%>
    <%= image_tag "study", class: "mySlides img-fluid"%>
    <%= image_tag "wok", class: "mySlides img-fluid"%>
  </div>
</div>
</div>
  <script type="text/javascript">
    var myIndex = 0;
    carousel();

    function carousel()
    {
      var i;
      var x = document.getElementsByClassName("mySlides");
      for (i = 0; i < x.length; i++) {
        x[i].style.display = "none";
      }
      myIndex++;
      if (myIndex > x.length) {myIndex = 1}
      x[myIndex-1].style.display = "block";
      setTimeout(carousel, 5000); // Change image every 2 seconds
    }
  </script>

  <div class="row">
    <div class="col-md-12" style="margin-top: -51px;">
   <p  class="pic2"></p>
   </div>
  </div>
  <div style="margin-top: -74px;" class="row">
    <div class="col-md-4">
  <div class="dropdown-show" style="margin-top: -15px; margin-left: 29px; padding-bottom: 13px;">
    <a class="btn btn-light dropdown-toggle" href="#" role="button" id="                             dropdownMenuLink" data-toggle="dropdown"> Menu
    </a>

    <div class="dropdown-menu" >
      <%= link_to 'visit', canada_visit_path(:visa), class: "dropdown-item" %>

      <%= link_to 'immigrant', canada_immigrant_path(:visa), class: "dropdown-item" %>

      <%= link_to 'study', canada_study_path(:visa), class: "dropdown-item" %>

      <%= link_to 'work', canada_work_path(:visa), class: "dropdown-item" %>
    </div>
  </div>
  </div>
    <div class="col-md-8">
       <div class="container">
    <marquee>
        <span>Avail your canada visa from here |</span>&nbsp;
        <span> Study visa |</span>&nbsp;
        <span>Immigration |</span>&nbsp;
        <span>Visit visa |</span>&nbsp;
        <span>Work permit visa |</span>&nbsp;
        <span>Best place to get any type of canada visa</span>
    </marquee>
  </div>
  </div>
</div>
       <div class="row">
      <div style="margin-top: 20px;" class="col-md-12">
        <%= image_tag "02", class: "img-fluid"%>
      </div>
      </div>
    <div class="container">
      <div class="wb-eight row wb-init">
      <div class="col-lg-4 col-md-6" style="vertical-align: top; min-height: 113px;">
        <h3 >Jobs</h3>
        <p class="a"></p>
        <p>Find a job, training, hiring programs,
        work permits, Social Insurance Number (SIN)</p>
      </div>
      <div class="col-lg-4 col-md-6" style="vertical-align: top; min-height: 113px;">
        <h3>Immigration&Citizenship</h3>
        <p class="b"></p>
        <p>Visit, work, study, immigrate, refugees, permanent residents, apply, check status</p>
      </div>
      <div class="col-lg-4 col-md-6" style="vertical-align: top; min-height: 113px;">
        <h3>Travel&Tourism</h3>
        <p class="c"></p>
        <p>In Canada or abroad, advice, advisories, passports, visit Canada, events, attractions</p>
      </div>
      <div class="col-lg-4 col-md-6" style="vertical-align: top; min-height: 113px;">
        <h3>Business&Industry</h3>
        <p class="d"></p>
        <p>Starting a business, permits, copyright, business support, selling to government</p>
      </div>
      <div class="col-lg-4 col-md-6" style="vertical-align: top; min-height: 113px;">
        <h3>Benefits</h3>
        <p class="e"></p>
        <p>EI, family and sickness leave, pensions, housing, student aid, disabilities</p>
      </div>
      <div  class="col-lg-4 col-md-6" style="vertical-align: top; min-height: 113px;">
        <h3>Health</h3>
        <p class="f"></p>
        <p>Food, nutrition, diseases, vaccines, drugs, product safety and recalls</p>
      </div>
    </div>
    <div class="mwsgeneric-base-html parbase section" id="n">
                <div style="float: right;">
             <%= image_tag "pi", class: "img-fluid" %>
           </div>
      <section class="home-your-gov gc-srvinfo well well-sm brdr-0">

        <div class="container" id="mm">
          <h2>Visa apply</h2>
          <div class="row mrgn-bttm-lg">
            <div class="col-lg-7 col-xs-12 col-md-6">
              <div class="wb-eqt row wb-init">
                <div class="col-lg-6" style="vertical-align: top; min-height: 113px;">
                  <h3><%= link_to "Contact us", canada_contact_us_path(:can), class: "j", target: "_blank" %></h3>
                  <p class="aa"></p>
                  <p>agency contacts,</p>
                </div>
                <div class="col-lg-6" style="vertical-align: top; min-height: 113px;">
                  <h3><%= link_to "Canada.ca", 'https://www.canada.ca/en.html', class: "j", target: "_blank"%></h3>
                  <p class="aa"></p>
                  <p>Canada immigration website</p>
                </div>
                <div class="col-lg-6" style="vertical-align: top; min-height: 113px;">
                      <h3><%= link_to "Alberta.ca", 'https://www.alberta.ca/immigration.aspx', class: "j", target: "_blank"%></h3>
                  <p class="aa"></p>
                  <p>Alberta home office & immigration</p>
                </div>
                <div class="col-lg-6" style="vertical-align: top; min-height: 113px;">
                  <h3><%= link_to "Ontario.ca", 'https://www.ontario.ca/page/citizenship-and-immigration', class: "j", target: "_blank"%></h3>
                  <p class="aa"></p>
                  <p>Ontario home office & immigration</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    <p class="mj"></p>
    </div>
        <div class="brand" style="margin-top: 80px;">
          <div class="container" style="margin-top: 26px; margin-bottom: 1px;">
            <div class="row">
              <nav class="col-md-10 ftr-urlt-lnk">
                <ul class="list-group flex-md-row">
                  <li style="margin-right: 27px;">Social-Media</li>
                  <li style="margin-right: 27px;">Mobile-Application</li>
                  <li style="margin-right: 27px;">Canada.Ca</li>
                  <li style="margin-right: 27px;">Term&Condition</li>
                  <li>Privacy</li>
                </ul>
              </nav>
              <div class="col-md-2 text-right" style="margin-left: -85px;">
                <%= link_to canada_main_path(:can) do %>
                <%= image_tag "last", class: "fluid" %>
                <%end %>
              </div>
            </div>
          </div>
        </div>
  </div>

</div>
</body>

app/views/canadas/main.html.erb
<body style="overflow-x: hidden;">
  <div class="container">
    <div class="row" style="margin-top: -32px;">
      <div class="col-md-3 o1">
        <%= link_to canadas_path do %>
         <%= image_tag "can1"%>
        <%end%>
      </div>
      <div class="col-md-9 o2" style="padding: 0px;">
        <%= image_tag "we", class: "mySlides img-fluid"%>
        <%= image_tag "visi", class: "mySlides img-fluid"%>
        <%= image_tag "imii", class: "mySlides img-fluid"%>
        <%= image_tag "study", class: "mySlides img-fluid"%>
        <%= image_tag "wok", class: "mySlides img-fluid"%>
      </div>
    </div>
    <script type="text/javascript">
      var myIndex = 0;
      carousel();

      function carousel()
      {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++)
        {
         x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) {myIndex = 1}
        x[myIndex-1].style.display = "block";
        setTimeout(carousel, 5000); // Change image every 2 seconds
      }
    </script>
    <div class="row">
      <div class="col-md-12" style="margin-top: -51px;">
        <p  class="pic2"></p>
      </div>
    </div>

    <div style="margin-top: -74px;" class="row">
      <div class="col-md-4">
        <div class="dropdown-show" style="margin-top: -15px;  margin-left: -28px;">
          <a class="btn btn-light dropdown-toggle" href="#" role="button" id="                               dropdownMenuLink" data-toggle="dropdown"> Menu
          </a>
          <div class="dropdown-menu" >
            <%= link_to 'visit', canada_visit_path(:visa), class: "dropdown-item" %>
            <%= link_to 'immigrant', canada_immigrant_path(:visa), class: "dropdown-item" %>
            <%= link_to 'study', canada_study_path(:visa), class: "dropdown-item" %>
            <%= link_to 'work', canada_work_path(:visa), class: "dropdown-item" %>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="container">
          <marquee>
            <span>Avail your canada visa from here |</span>&nbsp;
            <span> Study visa |</span>&nbsp;
            <span>Immigration |</span>&nbsp;
            <span>Visit visa |</span>&nbsp;
            <span>Work permit visa |</span>&nbsp;
            <span>Best place to get any type of canada visa</span>
          </marquee>
        </div>
      </div>
    </div>

      <div class="row">
       <div class="col-md-12">
          <h1 class="oo">List of all applicants canada</h1>
       </div>
      </div>

      <div class="row">
        <div  class="form-group col-md-4">
          <%= link_to 'New Apply', new_canada_path %><br><br>
        </div>
      </div>
      <div class="row">
        <div  class="form-group  col-md-4" style="margin-top: -24px;">
        <%= form_tag search_canadas_path(:can), :method => 'get' do %>
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>
        <%= submit_tag "search", class: " btn btn-dark sch" %>
        </div>
        <% end %>
      </div>
      <div class="table-responsive">
        <table class="table">
          <tr>
            <th>Application no</th>
            <th>First Name</th>
            <th>Nationality</th>
            <th>Passport no</th>
            <th>Visa category</th>
            <th>Application status</th>
            <th>Sponsor name</th>
          </tr>
          <% @canadas.each do |canada| %>
          <tr>
            <td><%= canada.application_no %></td>
            <td><%= canada.first_name %></td>
            <td><%= canada.nationality %></td>
            <td><%= canada.passport_no %></td>
            <td><%= canada.visa_category %></td>
            <td><%= canada.application_status %></td>
            <td><%= canada.sponsor_name %></td>
            <td><%= link_to 'show', canada_path(canada) %></td>
            <td><%= link_to 'edit', edit_canada_path(canada) %></td>
            <td><%= link_to "Delete", canada_path(canada), :confirm => "Are you sure?", :method => :delete %></td>
             <!--  <td><%= link_to "display", canada_display_path(canada, :id, format: 'pdf') %></td> -->
          </tr>
          <%end%>
        </table>
      </div>
      <div class="col-sm-12">
         <p class="float-right" style="margin-top: 196px;margin-right: -97px;">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.name %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
         <!--    <%= link_to "Sign up", new_user_registration_path %> -->

            <% else %>
            <%= link_to "Login", new_user_session_path %>

          <% end %>
        </p>
    </div>
    </div>
    <div class="brand1">
      <div class="container" style="margin-top: 26px; margin-bottom: 1px;">
        <div class="row">
          <nav class="col-sm-10 ftr-urlt-lnk">
            <ul class="list-group flex-md-row">
              <li style="margin-right: 27px;">Social-Media</li>
              <li style="margin-right: 27px;">Mobile-Application</li>
              <li style="margin-right: 27px;">Canada.Ca</li>
              <li style="margin-right: 27px;">Term&Condition</li>
              <li>Privacy</li>
            </ul>
          </nav>
          <div class="col-xs-6 col-md-2 text-right">
            <%= image_tag "last"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/canadas/visit.html.erb
<body style="overflow-x: hidden;">
  <div class="container">
    <div class="row" style="margin-top: -32px;">
      <div class="col-md-3 o1">
        <%= link_to canadas_path do %>
         <%= image_tag "can1"%>
        <%end%>
      </div>
      <div class="col-md-9 o2" style="padding: 0px;">
        <%= image_tag "we", class: "mySlides img-fluid"%>
        <%= image_tag "visi", class: "mySlides img-fluid"%>
        <%= image_tag "imii", class: "mySlides img-fluid"%>
        <%= image_tag "study", class: "mySlides img-fluid"%>
        <%= image_tag "wok", class: "mySlides img-fluid"%>
      </div>
    </div>
    <script type="text/javascript">
      var myIndex = 0;
      carousel();

      function carousel()
      {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++)
        {
         x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) {myIndex = 1}
        x[myIndex-1].style.display = "block";
        setTimeout(carousel, 5000); // Change image every 2 seconds
      }
    </script>
    <div class="row">
      <div class="col-md-12" style="margin-top: -51px;">
        <p  class="pic2"></p>
      </div>
    </div>

    <div style="margin-top: -74px;" class="row">
      <div class="col-md-4">
        <div class="dropdown-show" style="    margin-top: -26px;margin-left: -14px;padding: 11px;">
          <a class="btn btn-light dropdown-toggle" href="#" role="button" id="                               dropdownMenuLink" data-toggle="dropdown"> Menu
          </a>
          <div class="dropdown-menu" >
            <%= link_to 'visit', canada_visit_path(:visa), class: "dropdown-item" %>
            <%= link_to 'immigrant', canada_immigrant_path(:visa), class: "dropdown-item" %>
            <%= link_to 'study', canada_study_path(:visa), class: "dropdown-item" %>
            <%= link_to 'work', canada_work_path(:visa), class: "dropdown-item" %>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="container">
          <marquee style= "margin-left: -314px;">
            <span>Avail your canada visa from here |</span>&nbsp;
            <span> Study visa |</span>&nbsp;
            <span>Immigration |</span>&nbsp;
            <span>Visit visa |</span>&nbsp;
            <span>Work permit Visa |</span>&nbsp;
            <span>Best place to get any type of canada visa</span>
          </marquee>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row" style="margin-top: 16px;">
        <div class="col-lg-5" style="vertical-align: top; min-height: 113px;">
         <h1 class="kk">Visitor:visa Canada</h1>
            <p class="jj"></p>
            <p>Find out what document you need to travel, visit family and friends, do business, or transit through Canada, and how to extend your stay.</p>
        </div>
          <div class="col-md-7">
            <%= image_tag "visit", class: "img-fluid"%>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <h2><strong>Eligibility</strong></h2>
            <p>You must meet some basic requirements to get a visitor visa. You must:</p>
            <ul>
              <li>have a valid travel document, like a passport</li>
              <li>be in good health</li>
              <li>have no criminal or immigration-related convictions</li>
              <li>convince an immigration officer that you have ties—such as a job, home, financial assets or family—that will take you back to your home country</li>
              <li>convince an immigration officer that you will leave Canada at the end of your visit</li>
              <li>have enough money for your stay
                <ul>
                  <li>The amount of money you will need depends on how long you will stay and if you will stay in a hotel, or with friends or relatives.</li>
                </ul>
              </li>
            </ul>
            <p>You may also need a medical exam and letter of invitation from someone who lives in Canada.</p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="container">
             <h2><strong>Some people are not allowed to enter canada</strong></h2>
             <p>Some people are not admissible to Canada, which means they are not allowed to enter the country. You can be inadmissible for several reasons, including being involved in:</p>
             <ul>
                <li>criminal activity</li>
                <li>human rights violations</li>
                <li>organized crime</li>
              </ul>
              <p>You can also be inadmissible for security, health or financial reasons. Find out more about inadmissibility.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="container">
              <h2><strong>Minor children travelling to canada</strong></h2>
              <p>Make sure you know what to do if your minor children (children under the age of 18) will be travelling with you, with someone else, or alone.</p>
            </div>
          </div>
        </div>
      </div>
        <div style="text-align: center;">
          <%= link_to "Apply now", new_canada_path, class: "btn btn-dark"  %>
        </div>
        <div class="brand">
          <div class="container" style="margin-top: 26px; margin-bottom: 1px;">
            <div class="row">
              <nav class="col-sm-10 ftr-urlt-lnk">
                <ul class="list-group flex-md-row">
                  <li style="margin-right: 27px;">Social-Media</li>
                  <li style="margin-right: 27px;">Mobile-Application</li>
                  <li style="margin-right: 27px;">Canada.Ca</li>
                  <li style="margin-right: 27px;">Term&Condition</li>
                  <li>Privacy</li>
                </ul>
              </nav>
              <div class="col-xs-6 col-md-2 text-right" style="margin-left: -74px;">
                <%= link_to canada_main_path(:can) do %>
                <%= image_tag "last"%>
                <%end%>
              </div>
            </div>
          </div>
        </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>AgentApp</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= yield :meta %>
  <meta name="robots" content="index,follow">
  <title><%= yield :title %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true, :cache => "cache/all" %>
    <%= javascript_include_tag "application", :async => true, "data-turbolinks-track" => true, :cache => "cache/all" %>
        <%= wicked_pdf_stylesheet_link_tag "application" -%>
    <%= wicked_pdf_stylesheet_link_tag "bootstrap" %>
    <%= csrf_meta_tags %>
</head>
  <body>
    <%= yield %>
  </body>
</html>